runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"

handlers:
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /.*
  script: main.app
